---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mongo-snappcloud-io-v1-mongodbdata
  failurePolicy: Fail
  name: vmongodbdata.kb.io
  rules:
  - apiGroups:
    - mongo.snappcloud.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mongodbdata
  sideEffects: None
