# permissions for end users to view mongodbconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbconfig-viewer-role
rules:
- apiGroups:
  - mongo.snappcloud.io
  resources:
  - mongodbconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mongo.snappcloud.io
  resources:
  - mongodbconfigs/status
  verbs:
  - get
