name: Publish Docker image
on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
jobs:
  build_and_push:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE: mrjosh/mongodb-data-operator
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Go get packages
        run: go get .

      # https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md#multi-platform-image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action#install-by-default
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.GITHUB_REF_NAME }}
